/**
 * Requires a 'result.json' file generated by updateDatabase.js
 * 
 * I had to join "normal" and "special" forms, as there's no way to distinguish them.
 * For example, a Meloetta has two forms, and both the name and ID are the same.
 * However, only one of the two forms is actually good.
 * 
 * Negative search strings are STs that do not show those pokemon
 * Positive search strings are STs that only show those pokemon
 */

import { writeFileSync, readFileSync, existsSync } from 'fs'

if (!existsSync('result.json')) {
  console.log("No 'result.json' file found!")
  process.exit()
}

// ICEBOX: Create "that one" ST, with a bit margin of error, but that lazy people want to use who don't care much
// ICEBOX: Create "slightly less error prone" ST by not including shadow, megas and other forms, as people can take care of those individually
// ICEBOX: I should also probably allow the BE to always fetch like top 100, and then use this script here to programatically pick up to a certain amount

const pokemonNames = JSON.parse(readFileSync(`result.json`, 'utf8'));
const allPokemon = { positive: { shadow: [], mega: [], rest: [] }, negative: { shadow: [], mega: [], rest: [] } }

// Create organized array of Pokemon names
for (let type in pokemonNames) {
  // Join all 'normal' and 'other' forms
  for (let pokemon of pokemonNames[type]['default']) allPokemon.positive.rest.push(`+${pokemon}`)
  for (let pokemon of pokemonNames[type]['default']) allPokemon.negative.rest.push(`!+${pokemon}`)
  for (let pokemon of pokemonNames[type]['other']) allPokemon.positive.rest.push(`+${pokemon}`)
  for (let pokemon of pokemonNames[type]['other']) allPokemon.negative.rest.push(`!+${pokemon}`)

  // Join all 'shadow' forms
  for (let pokemon of pokemonNames[type]['shadow']) allPokemon.positive.shadow.push(`+${pokemon}`)
  for (let pokemon of pokemonNames[type]['shadow']) allPokemon.negative.shadow.push(`!+${pokemon}`)

  // Join all 'mega' forms
  for (let pokemon of pokemonNames[type]['mega']) allPokemon.positive.mega.push(`+${pokemon}`)
  for (let pokemon of pokemonNames[type]['mega']) allPokemon.negative.mega.push(`!+${pokemon}`)
}

const searchStrings = {
  positive: { shadow: 'shadow&', mega: 'mega0-&', rest: '!shadow,!mega0-&' },
  negative: { shadow: 'shadow&', mega: 'mega0-&', rest: '!shadow,!mega0-&' }
}

// Create search strings from arrays
searchStrings.positive.shadow += allPokemon.positive.shadow.join(',')
searchStrings.positive.mega += allPokemon.positive.mega.join(',')
searchStrings.positive.rest += allPokemon.positive.rest.join(',')

searchStrings.negative.shadow += allPokemon.negative.shadow.join('&')
searchStrings.negative.mega += allPokemon.negative.mega.join('&')
searchStrings.negative.rest += allPokemon.negative.rest.join('&')

// Save final search strings result to file
writeFileSync(`searchStrings.json`, JSON.stringify(searchStrings, null, 2))
